### ISSUE TITLE
Review: Manoa-Inventory-POST Admin Page

### ISSUE THREAD

**Issue by eduardokhojr** [Manoa-Inventory-POST/manoa-inventory-post#119]
## Overview

The focus for this code review will be centered around the admin page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-02

## Files to review

* [AdminDashboard.jsx](../blob/main/app/imports/ui/pages/AdminDashboard.jsx)
* [InfoBar.jsx](../blob/main/app/imports/ui/components/InfoBar.jsx)

## Checklists

* [Architecture](https://github.com/cammoore/414-review-checklists/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/414-review-checklists/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/414-review-checklists/blob/main/checklists/js-checklist.md)
* [React](https://github.com/cammoore/414-review-checklists/blob/main/checklists/react-checklist.md)
* [Testing](https://github.com/cammoore/414-review-checklists/blob/main/checklists/testing-checklist.md)

## Due date

Monday February 6, 2023

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by shannonkam** [comment]
**AdminDashboard.jsx**

- Design-05 (Line 20) Mentions Stuff documents
- JS-07 (Line 27) Get rid of console.log(admins)
- ESLINT-01 (Line 27) Unexpected console statement
- TEST-ACCEPTANCE-01 Doesn’t have isDisplayed() acceptance test

**InfoBar.jsx**

- Design-05 (Line 16) Mentions Stuff documents
- JS-07 (Line 23) Get rid of console.log(admins)
- ESLINT-01 (Line 23, 44, 50) Unexpected console statement and closing tag location

**Comment by lsollis** [comment]
AdminDashboard.jsx
Design-05 Ensure comments are appropriate (eliminate comments describing the how) line 14
JS-07 Avoid console.log line 27

InfoBar.jsx
Design-05 Ensure comments are appropriate (eliminate comments describing the how) line 10
ESLINT-01 Lines 41-44 fix indentation/line organization of code

**Comment by kaihe630** [comment]
**AdminDashboard.jsx**

1.  L20:  Comment about Stuff "// Get the Stuff documents"

**InfoBar.jsx**

1. L16: Comment about Stuff "// Get the Stuff documents"

Just bit more clean up

**Comment by zhixinliuh** [comment]
InfoBar.jsx
- line 16 still have stuff document
- fix comment overall 

AdminDashboard.jsx
- line 20 still have stuff document
- fix comment overall

**Comment by luoxiao11** [comment]
[InfoBar.jsx] Line 47-49: <Card.Link>changes line unexpectedly

**Comment by eduardokhojr** [comment]
**AdminDashboard.jsx**
Design: Stuff
JS & ES:. console log L-27

**InfoBar.jsx**
Design: Stuff

**Comment by yhanessaanne** [comment]
AdminDashboard.jsx
- Design 05: Line 20 Remove ```// Get the Stuff documents```
- Test-Acceptance 01: AdminDashboard page does have not have a isDisplayed() acceptance test.

InforBar.jsx
- Design 05: Line 17 Remove ```// Get the Stuff documents```

**Comment by justinjandoc** [comment]
## AdminDashboard.jsx
L20: Design-05: Remove Stuff comment
L21: Remove instances of Stuff
L27: JS-07: Remove console.log
## InfoBar.jsx
L23: JS-07: Remove console.log
