### ISSUE TITLE
Review: Manoa-Inventory-POST Faculty Home Page

### ISSUE THREAD

**Issue by eduardokhojr** [Manoa-Inventory-POST/manoa-inventory-post#206]
## Overview

The focus for this code review will be centered around the faculty home page.    
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-03

## Files to review

* [FacultyHome.jsx](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/app/imports/ui/pages/FacultyHome.jsx)
* [FacultyInfoBar.jsx](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/app/imports/ui/components/FacultyInfoBar.jsx)

## Checklists

* [Architecture](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/checklists/architecture-checklist.md)
* [Design](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/checklists/design-checklist.md)
* [JS](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/checklists/js-checklist.md)
* [React](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/checklists/react-checklist.md)
* [Testing](https://github.com/Manoa-Inventory-POST/manoa-inventory-post/blob/main/checklists/testing-checklist.md)

## Due date

February 13, 2023

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by zhixinliuh** [comment]
FacultyHome.jsx
-Correction on comment , clear stuff element
-add comment
FacultyInfoBar.jsx
-Correction on comment , ckear stuff element
-herf link needs to be added

**Comment by lsollis** [comment]
FacultyHome.jsx
Design-05: Ensure comments are appropriate - copy/paste error comments (lines 11, 15, 19); get rid of “how” comments (line 13)
JS-07: Avoid console.logs (line 26)
ESLINT-01: No errors, avoid warnings move import meteor before component imports

FacultyInfoBar.jsx
JS-07: Avoid console.logs (line 23)

**Comment by yhanessaanne** [comment]
FacultyHome.jsx
DE-05: L11, L13, L15, L19

FacultyInfoBar.jsx
DE-05: L1, L12, L16

**Comment by shannonkam** [comment]
**FacultyHome.jsx**

- DE-05 (Line 11, 19) Mentions Stuff
- JS-06 (Line 26) Get rid of console.log(faculty)
- ES-01 (Line 9, 25, 46, 26) Import order, indentation, blank lines, and unexpected console statement
- TA-01 Doesn’t have isDisplayed() acceptance test

**FacultyInfoBar.jsx**

- DE-05 (Line 9, 16) Mentions admin dashboard and stuff
- JS-06 (Line 23) Get rid of console.log(faculty)
- ES-01 (Line 23) Unexpected console statement

**Comment by justinjandoc** [comment]
## FacultyHome.jsx
L11, 19: DE-05: Edit comments to not include mentions of Stuff
L11, 15: DE-05: Edit comments to replace Admin with Faculty
L26: JS-05: Remove console.log

## FacultyInfoBar.jsx
L12: DE-05: Edit comment to replace Admin with Faculty
L16: DE-05: Edit comment to not include mentions of Stuff
L23: JS-05: Remove console.log

**Comment by eduardokhojr** [comment]
**FacultyHome.jsx:**
Design: L11 - stuff comment
JS & ES: L26 - console log

**FacultyInfoBar.jsx:**
Design: L16 - stuff comment
JS & ES: L23 - console log

**Comment by luoxiao11** [comment]
FacultyInfoBar.jsx: Line 23: remove console.log()

**Comment by kaihe630** [comment]
**FacultyHome.jsx:**
L11 & 19: Comments about stuff

**FacultyInfoBar.jsx:**
L16: Comments about stuff

Clear out the old comment
