### ISSUE TITLE
Review: Manoa-Inventory-POST Landing

### ISSUE THREAD

**Issue by eduardokhojr** [Manoa-Inventory-POST/manoa-inventory-post#75]
## Overview

The focus for this code review will be centered around the Landing page.    

Please pay attention too:
* Javascript issues
* React components

## Review Branch

issue-15

## Files to review

* [Landing.jsx](../blob/main/app/imports/ui/pages/Landing.jsx)
* [NavBar.jsx](../blob/main/app/imports/ui/components/NavBar.jsx)

## Checklists

* [Architecture](../blob/main/checklists/architecture-checklist.md)
* [Design](../blob/main/checklists/design-checklist.md)
* [JS](../blob/main/checklists/js-checklist.md)
* [React](../blob/main/checklists/react-checklist.md)
* [Testing](../blob/main/checklists/testing-checklist.md)

## Due date

January 30, 2023

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by justinjandoc** [comment]
## Landing.jsx
DE-05: Adding comments would improve readability.
L22, 23: ES-01: Consider breaking line up rather than disabling ESLint.

## NavBar.jsx
DE-05: Adding comments would improve readability.
L35: NavLink to NAVBAR_LIST_STUFF_ADMIN is not needed.

**Comment by kaihe630** [comment]
Landing.jsx
L22,23: ES-01: There is an Eslint error of too many words in one line. 

NavBar.jsx
Looks fine...

Not sure if the Esline error means a lot or if it has a proper way to fix it.

**Comment by lsollis** [comment]
**Landing.jsx**
REACT-01: consider using components/subcomponents to break up the page
DESIGN-01: refactor to reduce duplication

**Comment by zhixinliuh** [comment]
Navbar.jsx:
35 :Remove all stuff page or item

**Comment by yhanessaanne** [comment]
Landing.jsx: 
Design: Ensure DRY

Navbar.jsx: 
Design: Add in comments for readability

**Comment by shannonkam** [comment]
**Landing.jsx**
ES-01 (Line 22-23) Too many words in one line 

**NavBar.jsx**
Nothing

**Comment by eduardokhojr** [comment]
**Landing.jsx**
ES: Max length but we got to do what we got to do
Design: Add Comments
**NavBar.jsx**
Design: Add Comments

**Comment by luoxiao11** [comment]
Line 20, 37 etc. are long, consider break them into multiple lines to make it more readable
